CREATE TABLE sources (
 id text PRIMARY KEY, enabled boolean NOT NULL DEFAULT true, coverage_since date NOT NULL,
 last_started timestamptz, last_success timestamptz, newest_record date, error text, next_run timestamptz
);
CREATE TABLE runs (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_id text NOT NULL REFERENCES sources,
 status text NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','running','success','failed')),
 queued_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, finished_at timestamptz,
 fetched integer NOT NULL DEFAULT 0, new_permits integer NOT NULL DEFAULT 0, changed integer NOT NULL DEFAULT 0,
 duplicates integer NOT NULL DEFAULT 0, leads_created integer NOT NULL DEFAULT 0, error text
);
CREATE UNIQUE INDEX one_active_run ON runs(source_id) WHERE status IN ('queued','running');
CREATE TABLE projects (project_key text PRIMARY KEY, first_seen timestamptz NOT NULL DEFAULT now());
CREATE TABLE permits (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, jurisdiction text NOT NULL, permit_number text NOT NULL,
 project_key text NOT NULL REFERENCES projects, payload jsonb NOT NULL, payload_hash text NOT NULL,
 first_seen timestamptz NOT NULL DEFAULT now(), last_seen timestamptz NOT NULL DEFAULT now(), UNIQUE(jurisdiction,permit_number)
);
CREATE INDEX permit_project ON permits(project_key);
CREATE TABLE raw_events (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source_id text NOT NULL REFERENCES sources,
 permit_id integer NOT NULL REFERENCES permits, payload_hash text NOT NULL, fetched_at timestamptz NOT NULL DEFAULT now(),
 payload jsonb NOT NULL, UNIQUE(source_id,permit_id,payload_hash)
);
CREATE INDEX event_permit ON raw_events(permit_id);
CREATE TABLE leads (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, project_key text NOT NULL REFERENCES projects,
 trade text NOT NULL, active boolean NOT NULL DEFAULT true, payload jsonb NOT NULL,
 first_seen timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
 status text NOT NULL DEFAULT 'New' CHECK(status IN ('New','Qualified','Contacted','Sold','Dismissed')),
 saved boolean NOT NULL DEFAULT false, notes text NOT NULL DEFAULT '', assigned_to text NOT NULL DEFAULT '',
 city text GENERATED ALWAYS AS (payload->>'city') STORED,
 state text GENERATED ALWAYS AS (payload->>'state') STORED,
 stage text GENERATED ALWAYS AS (payload->>'stage') STORED,
 signal_date text GENERATED ALWAYS AS (payload->>'signal_date') STORED,
 UNIQUE(project_key,trade)
);
CREATE INDEX lead_filters ON leads(active,trade,state,city,signal_date);
CREATE INDEX lead_saved ON leads(state) WHERE saved;
CREATE TABLE property_enrichment (apn text PRIMARY KEY, fetched_at timestamptz NOT NULL DEFAULT now(), payload jsonb NOT NULL);
CREATE TABLE geocode_cache (
 address_key text PRIMARY KEY, address jsonb NOT NULL, status text NOT NULL, latitude double precision, longitude double precision,
 matched_address text NOT NULL DEFAULT '', fetched_at timestamptz, expires_at timestamptz, attempts integer NOT NULL DEFAULT 0,
 retry_at timestamptz, benchmark text NOT NULL DEFAULT 'Public_AR_Current'
);
CREATE TABLE lead_locations (
 lead_id integer PRIMARY KEY REFERENCES leads, address_key text NOT NULL,
 latitude double precision CHECK(latitude BETWEEN -90 AND 90), longitude double precision CHECK(longitude BETWEEN -180 AND 180),
 provider text NOT NULL DEFAULT '', match_method text NOT NULL DEFAULT '', matched_address text NOT NULL DEFAULT '',
 fetched_at timestamptz, expires_at timestamptz, status text NOT NULL DEFAULT 'pending'
);
CREATE INDEX location_coordinates ON lead_locations(latitude,longitude);
CREATE INDEX location_address ON lead_locations(address_key);
CREATE TABLE enrichment_results (
 cache_key text PRIMARY KEY, kind text NOT NULL, provider text NOT NULL, payload jsonb NOT NULL,
 fetched_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL
);
CREATE TABLE enrichment_aliases (lookup_key text PRIMARY KEY, owner_key text NOT NULL);
CREATE TABLE enrichment_reviews (
 owner_key text PRIMARY KEY, owner_hash text NOT NULL DEFAULT '', owner_type text NOT NULL DEFAULT 'Unknown',
 reviewed boolean NOT NULL DEFAULT false, contact_hash text NOT NULL DEFAULT '', contacts_verified boolean NOT NULL DEFAULT false,
 suppressed boolean NOT NULL DEFAULT false
);
CREATE INDEX suppressed_identity ON enrichment_reviews(owner_hash) WHERE suppressed;
CREATE TABLE enrichment_jobs (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, lead_id integer NOT NULL REFERENCES leads,
 cache_key text NOT NULL, kind text NOT NULL CHECK(kind IN ('owner','contacts')), status text NOT NULL DEFAULT 'queued',
 queued_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz, message text NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX enrichment_pending ON enrichment_jobs(cache_key,kind) WHERE status IN ('queued','running');
CREATE TABLE trial_usage (provider text NOT NULL, trial_id text NOT NULL, units integer NOT NULL DEFAULT 0 CHECK(units>=0), PRIMARY KEY(provider,trial_id));
-- Great-circle distance in miles; keeps existing radius semantics without requiring an extension.
CREATE FUNCTION distance_miles(lat double precision, lon double precision, center_lat double precision, center_lon double precision)
RETURNS double precision LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
 SELECT 3958.7613 * 2 * asin(sqrt(least(1.0,greatest(0.0,
 power(sin(radians(center_lat-lat)/2),2)+cos(radians(lat))*cos(radians(center_lat))*power(sin(radians(center_lon-lon)/2),2)))))
$$;
